import { Category, MenuItem, BusinessSettings } from './types';

export const CATEGORIES: Category[] = [
  { id: 'main', name: 'Grills', nameAr: 'المشويات', icon: 'ChefHat' },
  { id: 'shawarma', name: 'Shawarma', nameAr: 'قسم الشاورما', icon: 'Flame' },
  { id: 'appetizers', name: 'Appetizers', nameAr: 'المقبلات', icon: 'Salad' },
  { id: 'desserts', name: 'Desserts', nameAr: 'الحلويات', icon: 'IceCream' },
  { id: 'drinks', name: 'Drinks', nameAr: 'المشروبات', icon: 'GlassWater' },
  { id: 'coffee', name: 'Arabic Coffee', nameAr: 'القهوة العربية', icon: 'Coffee' },
  { id: 'games', name: 'Traditional Games', nameAr: 'الألعاب الشعبية', icon: 'Gamepad2' }
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // Grills Section
  {
    id: 'g1',
    name: 'Beef Kabab (4 Skewers)',
    nameAr: 'كباب لحم نفر 4 سيخ',
    description: 'Fresh grilled beef kabab served with bread and salad.',
    descriptionAr: 'نفر كباب لحم طازج مشوي على الجمر يقدم مع الخبز الحار.',
    price: 25,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?auto=format&fit=crop&q=80&w=600',
    calories: 580,
    isPopular: true,
    isAvailable: true,
  },
  {
    id: 'g2',
    name: 'Beef Kabab Kilo (16 Skewers)',
    nameAr: 'كيلو كباب لحم 16 سيخ',
    description: 'One kilo of beef kabab for sharing.',
    descriptionAr: 'كيلو كامل من كباب اللحم الطازج المشوي على الفحم.',
    price: 95,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&q=80&w=600',
    calories: 2200,
    isAvailable: true,
  },
  {
    id: 'g3',
    name: 'Mixed Grills Kilo (16 Skewers)',
    nameAr: 'كيلو مشكل 16 سيخ',
    description: 'A mix of various grilled meats, perfect for families.',
    descriptionAr: 'كيلو مشكل يجمع بين الكباب والأوصال والشيش طاووق.',
    price: 100,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=600',
    calories: 2100,
    isPopular: true,
    isAvailable: true,
  },
  {
    id: 'g4',
    name: 'Beef Awsal Kilo (16 Skewers)',
    nameAr: 'كيلو اوصال لحم 16 سيخ',
    description: 'Tender beef cubes grilled to perfection.',
    descriptionAr: 'قطع لحم أوصال طرية متبلة تتبيلة رحلة شواء الخاصة.',
    price: 140,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?auto=format&fit=crop&q=80&w=600',
    calories: 1900,
    isAvailable: true,
  },
  {
    id: 'g5',
    name: 'Chicken Kabab (4 Skewers)',
    nameAr: 'كباب دجاج نفر 4 سيخ',
    description: 'Grilled chicken kabab with balanced spices.',
    descriptionAr: 'نفر مشويات مشكل دجاج (كباب وشيش طاووق) مشوي على الفحم.',
    price: 23,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&q=80&w=600',
    calories: 520,
    isAvailable: true,
  },
  {
    id: 'g6',
    name: 'Beef Kabab Sarookh',
    nameAr: 'صاروخ كباب لحم',
    description: 'Beef kabab wrap with our signature sauce.',
    descriptionAr: 'ساندوتش كباب لحم بخبز الصاج مع الصلصة الخاصة.',
    price: 12,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1626700051175-656a433bcfef?auto=format&fit=crop&q=80&w=600',
    calories: 420,
    isAvailable: true,
  },
  {
    id: 'g7',
    name: 'Shish Taouk (4 Skewers)',
    nameAr: 'شيش طاووق نفر 4 سيخ',
    description: 'Marinated chicken breast cubes grilled on skewers.',
    descriptionAr: 'قطع صدر دجاج متبلة بالزبادي والليمون مشوية بإتقان.',
    price: 22,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eea50f5?auto=format&fit=crop&q=80&w=600',
    calories: 460,
    isAvailable: true,
  },
  {
    id: 'g8',
    name: 'Chicken Kabab Kilo (16 Skewers)',
    nameAr: 'كيلو كباب دجاج 16 سيخ',
    description: 'One kilo of seasoned chicken kabab.',
    descriptionAr: 'كيلو كامل من كباب الدجاج المشوي نكهة لا تقاوم.',
    price: 80,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1599481238332-b280300d53c6?auto=format&fit=crop&q=80&w=600',
    calories: 1800,
    isAvailable: true,
  },
  {
    id: 'g9',
    name: 'Shish Kilo (16 Skewers)',
    nameAr: 'كيلو شيش 16 سيخ',
    description: 'One kilo of our famous shish taouk.',
    descriptionAr: 'كيلو كامل من الشيش طاووق المتبل، جاهز للمشاركة.',
    price: 85,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1518492104633-130d0cc84637?auto=format&fit=crop&q=80&w=600',
    calories: 1750,
    isAvailable: true,
  },
  {
    id: 'g10',
    name: 'Beef Awsal (4 Skewers)',
    nameAr: 'أوصال لحم نفر 4 سيخ',
    description: 'Grilled tender beef slices served with appetizers.',
    descriptionAr: 'نفر أوصال لحم طرية مشوية تقدم مع خضروات مشوية.',
    price: 35,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6e9481bfa?auto=format&fit=crop&q=80&w=600',
    calories: 620,
    isAvailable: true,
  },
  {
    id: 'g11',
    name: 'Beef Awsal Sarookh',
    nameAr: 'صاروخ اوصال لحم',
    description: 'Beef cubes wrap with fresh veggies and tahini.',
    descriptionAr: 'ساندوتش أوصال لحم صاروخ مع الخضار المشوي والطحينة.',
    price: 18,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1619194472461-a1293e660144?auto=format&fit=crop&q=80&w=600',
    calories: 450,
    isAvailable: true,
  },
  {
    id: 'g12',
    name: 'Chicken Kabab Sarookh',
    nameAr: 'صاروخ كباب دجاج',
    description: 'Juicy chicken kabab wrap with garlic sauce.',
    descriptionAr: 'ساندوتش كباب دجاج صاروخ مع الثومية والبطاطس.',
    price: 10,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&q=80&w=600',
    calories: 380,
    isAvailable: true,
  },
  {
    id: 'g13',
    name: 'Shish Sarookh',
    nameAr: 'صاروخ شيش',
    description: 'Grilled shish taouk wrap with special garlic paste.',
    descriptionAr: 'ساندوتش شيش طاووق صاروخ مع الثومية والمخلل المقرمش.',
    price: 10,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&q=80&w=600',
    calories: 400,
    isAvailable: true,
  },
  // Shawarma Section
  {
    id: 's1',
    name: 'Sarookh Shawarma',
    nameAr: 'شاورما صاروخ',
    description: 'Large shawarma wrap with our special BBQ sauce and garlic dip.',
    descriptionAr: 'شاورما دجاج صاروخ بخبز الصاج المميز مع الثومية والبطاطس.',
    price: 9,
    category: 'shawarma',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&q=80&w=600',
    calories: 450,
    isPopular: true,
    isAvailable: true,
  },
  {
    id: 's2',
    name: 'Small Shawarma',
    nameAr: 'شاورما صغير',
    description: 'Classic small shawarma wrap, perfect for a quick snack.',
    descriptionAr: 'شاورما دجاج كلاسيك حجم صغير لمحبي الوجبات الخفيفة.',
    price: 5,
    category: 'shawarma',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&q=80&w=600',
    calories: 280,
    isAvailable: true,
  },
  {
    id: 's3',
    name: 'BBQ Shawarma',
    nameAr: 'شاورما شواء (وجبة)',
    description: 'Special shawarma prepared with traditional BBQ techniques.',
    descriptionAr: 'شاورما دجاج مدخنة محضرة على طريقة شواء الخاصة.',
    price: 15,
    category: 'shawarma',
    image: 'https://images.unsplash.com/photo-1662116765994-1e0026369527?auto=format&fit=crop&q=80&w=600',
    calories: 520,
    isPopular: true,
    isAvailable: true,
  },
  {
    id: 's4',
    name: 'Medium Arabic Plate',
    nameAr: 'صحن عربي وسط',
    description: 'Sliced shawarma pieces served with fries, garlic, and pickles.',
    descriptionAr: 'قطع شاورما مقطعة تقدم مع البطاطس، الثومية والمخلل.',
    price: 15,
    category: 'shawarma',
    image: 'https://images.unsplash.com/photo-1593001874117-c99c800e3eb7?auto=format&fit=crop&q=80&w=600',
    calories: 750,
    isAvailable: true,
  },
  {
    id: 's5',
    name: 'Large Arabic Plate',
    nameAr: 'صحن عربي كبير',
    description: 'A generous portion of sliced shawarma with extra sides.',
    descriptionAr: 'صحن عربي كبير مشكل مع خبز محمص، بطاطس ومقبلات كثيرة.',
    price: 20,
    category: 'shawarma',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600',
    calories: 980,
    isAvailable: true,
  },
  {
    id: 's6',
    name: 'Shawarma Box',
    nameAr: 'بوكس الشاورما',
    description: 'Group box featuring multiple shawarma wraps and appetizers.',
    descriptionAr: 'بوكس عائلي منوع كافي ووافي من الشاورما والمقبلات.',
    price: 60,
    category: 'shawarma',
    image: 'https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&q=80&w=600',
    calories: 2400,
    isPopular: true,
    isAvailable: true,
  },
  {
    id: 's7',
    name: 'Chicken Fries',
    nameAr: 'تشكن فرايز',
    description: 'Crispy fries topped with chicken shawarma and sauces.',
    descriptionAr: 'بطاطس مقلية مغطاة بقطع الشاورما والصلصات الخاصة والهلابينو.',
    price: 13,
    category: 'shawarma',
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&q=80&w=600',
    calories: 620,
    isAvailable: true,
  },
  {
    id: 's8',
    name: 'Cheese Fries',
    nameAr: 'بطاطس بالجبنة',
    description: 'Loaded fries with melted cheese blend.',
    descriptionAr: 'بطاطس مقلية ذهبية مغطاة بكريمة الجبن السائلة.',
    price: 7,
    category: 'shawarma',
    image: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&q=80&w=600',
    calories: 480,
    isAvailable: true,
  },
  // Appetizers Section
  {
    id: 'a1',
    name: 'Hummus',
    nameAr: 'حمص',
    description: 'Creamy chickpea dip with tahini and olive oil.',
    descriptionAr: 'حمص ناعم ومميز محضر بالطحينة وزيت الزيتون.',
    price: 7,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1547058881-aa0edd92aab3?auto=format&fit=crop&q=80&w=600',
    calories: 250,
    isPopular: true,
    isAvailable: true,
  },
  {
    id: 'a2',
    name: 'Mutabbal',
    nameAr: 'متبل',
    description: 'Smoked eggplant dip with tahini.',
    descriptionAr: 'باذنجان مشوي ومتبل بالطحينة والزبادي.',
    price: 7,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&q=80&w=600',
    calories: 180,
    isAvailable: true,
  },
  // Desserts Section
  {
    id: 'd1',
    name: 'Cheese Beehive Bread',
    nameAr: 'خلية جبن',
    description: 'Soft honeycomb bread stuffed with cream cheese and drizzled with honey.',
    descriptionAr: 'خلية نحل هشة محشوة بالجبنة الكريمية ومغطاة بالعسل الطبيعي.',
    price: 10,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&q=80&w=600',
    calories: 420,
    isPopular: true,
    isAvailable: true,
  },
  {
    id: 'd2',
    name: 'Chocolate Beehive Bread',
    nameAr: 'خلية شوكليت',
    description: 'Fresh baked honeycomb bread filled with melted chocolate.',
    descriptionAr: 'خلية نحل هشة محشوة بقطع الشوكولاتة الذائبة.',
    price: 10,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1551024601-5f3327c53ef1?auto=format&fit=crop&q=80&w=600',
    calories: 480,
    isAvailable: true,
  },
  {
    id: 'd3',
    name: 'Date Cake',
    nameAr: 'كيكة التمر',
    description: 'Moist date sponge cake served with a drizzle of date syrup.',
    descriptionAr: 'كيكة تمر هشة ومميزة تقدم مع دبس التمر الطبيعي.',
    price: 4,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&q=80&w=600',
    calories: 220,
    isAvailable: true,
  },
  {
    id: 'd4',
    name: 'Basbousa',
    nameAr: 'بسبوسة',
    description: 'Traditional semolina cake soaked in syrup and topped with almonds.',
    descriptionAr: 'بسبوسة شرقية تقليدية مرملة ومشربة بالقطر.',
    price: 4,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1589119614234-dd4fc9b3cf23?auto=format&fit=crop&q=80&w=600',
    calories: 180,
    isAvailable: true,
  },
  {
    id: 'd5',
    name: 'Souffle',
    nameAr: 'سوفليه',
    description: 'Warm chocolate souffle with a molten center.',
    descriptionAr: 'سوفليه شوكولاتة دافئ يذوب في الفم.',
    price: 4,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1511911063855-2bf39afa5b2e?auto=format&fit=crop&q=80&w=600',
    calories: 320,
    isAvailable: true,
  },
  {
    id: 'd6',
    name: 'Cinnabon',
    nameAr: 'سينابون',
    description: 'Freshly baked cinnamon roll topped with cream cheese frosting.',
    descriptionAr: 'لفائف القرفة الطازجة مع صوص الكريمة اللذيذ.',
    price: 5,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?auto=format&fit=crop&q=80&w=600',
    calories: 350,
    isAvailable: true,
  },
  // Drinks Section
  {
    id: 'dr1',
    name: 'Pepsi',
    nameAr: 'بيبسي',
    description: 'Refreshing carbonated soft drink.',
    descriptionAr: 'مشروب غازي بيبسي بارد ومنعش.',
    price: 2.5,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=600',
    calories: 140,
    isAvailable: true,
  },
  {
    id: 'dr2',
    name: 'Pepsi Diet',
    nameAr: 'بيبسي دايت',
    description: 'Sugar-free carbonated soft drink.',
    descriptionAr: 'مشروب بيبسي دايت خالي من السكر.',
    price: 2.5,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=600',
    calories: 0,
    isAvailable: true,
  },
  {
    id: 'dr3',
    name: 'Mountain Dew',
    nameAr: 'ماونتن ديو',
    description: 'Citrus-flavored carbonated soft drink.',
    descriptionAr: 'مشروب غازي ديو بنكهة الحمضيات المنعشة.',
    price: 2.5,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1625772291426-f15cd4428a2c?auto=format&fit=crop&q=80&w=600',
    calories: 170,
    isAvailable: true,
  },
  {
    id: 'dr4',
    name: 'Mountain Dew Diet',
    nameAr: 'ماونتن ديو دايت',
    description: 'Sugar-free citrus carbonated soft drink.',
    descriptionAr: 'مشروب ديو دايت منعش خالي من السكر.',
    price: 2.5,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1625772291426-f15cd4428a2c?auto=format&fit=crop&q=80&w=600',
    calories: 0,
    isAvailable: true,
  },
  {
    id: 'dr5',
    name: '7UP',
    nameAr: 'سفن أب',
    description: 'Lemon-lime carbonated soft drink.',
    descriptionAr: 'مشروب غازي سفن أب بنكهة الليمون.',
    price: 2.5,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&q=80&w=600',
    calories: 140,
    isAvailable: true,
  },
  {
    id: 'dr5d',
    name: '7UP Diet',
    nameAr: 'سفن أب دايت',
    description: 'Sugar-free lemon-lime carbonated soft drink.',
    descriptionAr: 'مشروب سفن أب دايت خالي من السكر.',
    price: 2.5,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&q=80&w=600',
    calories: 0,
    isAvailable: true,
  },
  {
    id: 'dr6',
    name: 'Citrus Hamidiyat',
    nameAr: 'حمضيات',
    description: 'Refreshing citrus flavored soft drink.',
    descriptionAr: 'مشروب حمضيات منعش ولذيذ.',
    price: 2.5,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1548195667-1d329af0a475?auto=format&fit=crop&q=80&w=600',
    calories: 160,
    isAvailable: true,
  },
  {
    id: 'dr7',
    name: 'Mineral Water (Small)',
    nameAr: 'مياه معدنية صغير',
    description: 'Fresh mineral water bottle.',
    descriptionAr: 'مياه معدنية باردة حجم صغير.',
    price: 0.5,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1608885898957-a599fb18ec3f?auto=format&fit=crop&q=80&w=600',
    calories: 0,
    isAvailable: true,
  },
  {
    id: 'dr8',
    name: 'Mineral Water (Large)',
    nameAr: 'مياه معدنية كبير',
    description: 'Fresh mineral water bottle.',
    descriptionAr: 'مياه معدنية باردة حجم كبير.',
    price: 1,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1608885898957-a599fb18ec3f?auto=format&fit=crop&q=80&w=600',
    calories: 0,
    isAvailable: true,
  },
  {
    id: 'dr9',
    name: 'Rabie Juice',
    nameAr: 'عصير ربيع',
    description: 'Assorted fruit juice by Rabie.',
    descriptionAr: 'عصير ربيع مشكل بنكهات الفواكه.',
    price: 2,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=600',
    calories: 90,
    isAvailable: true,
  },
  // Coffee Section
  {
    id: 'c1',
    name: 'Plain Arabic Coffee',
    nameAr: 'قهوة سادة',
    description: 'Traditional Arabic coffee pot served with premium dates.',
    descriptionAr: 'زمزمية قهوة سادة مع تمر فاخر.',
    price: 10,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1544145945-f904253db0ad?auto=format&fit=crop&q=80&w=600',
    calories: 50,
    isPopular: true,
    isAvailable: true,
  },
  {
    id: 'c2',
    name: 'Cloves Arabic Coffee',
    nameAr: 'قهوة قرنفل',
    description: 'Aromatic Arabic coffee with cloves, served with dates.',
    descriptionAr: 'زمزمية قهوة بنكهة القرنفل مع تمر.',
    price: 10,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1621506289937-23f46f48a04b?auto=format&fit=crop&q=80&w=600',
    calories: 55,
    isAvailable: true,
  },
  {
    id: 'c3',
    name: 'Cardamom Arabic Coffee',
    nameAr: 'قهوة هيل',
    description: 'Classic Arabic coffee with cardamom, served with dates.',
    descriptionAr: 'زمزمية قهوة بالهيل مع تمر.',
    price: 10,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    calories: 55,
    isAvailable: true,
  },
  // Traditional Games Section
  {
    id: 'gm1',
    name: 'Baloot',
    nameAr: 'بلوت',
    description: 'Enjoy a game of Baloot with your friends.',
    descriptionAr: 'استمتع بلعبة البلوت مع أصدقائك في جو تراثي.',
    price: 10,
    category: 'games',
    image: 'https://images.unsplash.com/photo-1611195974226-a6a9be9dd763?auto=format&fit=crop&q=80&w=600',
    calories: 0,
    isAvailable: true,
  },
  {
    id: 'gm2',
    name: 'Jakaroo',
    nameAr: 'جاكارو',
    description: 'Strategic board game for four players.',
    descriptionAr: 'لعبة جاكارو الاستراتيجية الممتعة لمجموعة من ٤ أشخاص.',
    price: 10,
    category: 'games',
    image: 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?auto=format&fit=crop&q=80&w=600',
    calories: 0,
    isAvailable: true,
  },
  {
    id: 'gm3',
    name: 'Dominoes',
    nameAr: 'دومنا',
    description: 'Classic dominoes set for a chill time.',
    descriptionAr: 'لعبة الدومنا الكلاسيكية لقضاء وقت ممتع.',
    price: 10,
    category: 'games',
    image: 'https://images.unsplash.com/photo-1566694271453-390536dd1f0d?auto=format&fit=crop&q=80&w=600',
    calories: 0,
    isAvailable: true,
  },
  {
    id: 'gm4',
    name: 'Trix',
    nameAr: 'تركس',
    description: 'Traditional card game.',
    descriptionAr: 'لعبة الورق التقليدية (تركس) بجلسة مريحة.',
    price: 10,
    category: 'games',
    image: 'https://images.unsplash.com/photo-1611195974226-a6a9be9dd763?auto=format&fit=crop&q=80&w=600',
    calories: 0,
    isAvailable: true,
  },
  {
    id: 'gm5',
    name: 'Carrom',
    nameAr: 'كيرم',
    description: 'Traditional tabletop game.',
    descriptionAr: 'لعبة الكيرم التراثية لمحبي التحدي.',
    price: 10,
    category: 'games',
    image: 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?auto=format&fit=crop&q=80&w=600',
    calories: 0,
    isAvailable: true,
  }
];

export const DEFAULT_BUSINESS_SETTINGS: BusinessSettings = {
  restaurantNameAr: "رحلة شواء",
  restaurantNameEn: "Grilling Journey",
  taglineAr: "مذاق المشويات الفاخرة على أصولها",
  taglineEn: "The Authentic Taste of Premium Grills",
  logoUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=200",
  phone: "0501234567",
  whatsappNumber: "966501234567",
  addressAr: "الرياض، المملكة العربية السعودية",
  addressEn: "Riyadh, Kingdom of Saudi Arabia",
  taxEnabled: true,
  taxPercent: 15,
  taxMethod: 'inclusive',
  vatNumber: "310123456700003",
  workingHoursStart: "17:00",
  workingHoursEnd: "02:00",
  receiptWidth: "80mm",
  receiptFontSize: 11,
  receiptLogoSize: 80,
  showKitchenSlipOnPrint: true,
  showCustomerReceiptOnPrint: true,
  kitchenSlipFontSize: 12,
  kitchenSlipHeaderAr: "فاتورة تحضير المطبخ",
  kitchenSlipHeaderEn: "Kitchen Preparation Slip",
  invoiceFooterAr: "شكراً لزيارتكم! بالهناء والشفاء",
  invoiceFooterEn: "Thank you for dining with us!",
  bankNameAr: "مصرف الراجحي",
  bankNameEn: "Al Rajhi Bank",
  bankAccountNameAr: "مؤسسة رحلة شواء لتقديم الوجبات",
  bankAccountNameEn: "Grilling Journey Meals Est.",
  bankAccountNumber: "432608010007890",
  bankIban: "SA8380000432608010007890",
  bankQrUrl: "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=432608010007890",
  bankEnabled: true,
  deliveryFee: 15
};
